#!/bin/bash

# if rofi >= 1.5.2 "Lock \x00icon\x1ffile-browser," works

entries="Logout\nLock\nSuspend\nReboot\nShutdown"

selected=$(echo -e $entries | rofi  -dmenu -p "Power:" -i )

case $selected in
  Lock) 
    exec swaylock;;
  Logout)
    swaymsg exit;;
  Suspend)
    exec systemctl suspend;;
  Reboot)
    exec systemctl reboot;;
  Shutdown)
    exec systemctl poweroff -i;;
esac
